[config]
skip_core_tasks = true

[tasks.build]
description = "Runs the rust compiler."
category = "Build"
install_crate = false
command = "cargo"
args = [
    "build",
    "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
    "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]

[tasks.fmt-check]
description = "Runs the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.test]
command = "cargo"
args = ["test", "${@}", "--all-features"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "-D", "warnings"]

[tasks.docs]
description = "Build docs as they are rendered on docs.rs"
command = "cargo"
args = ["doc", "--document-private-items", "--all-features", "--no-deps"]
env = { "RUSTDOCFLAGS" = "-Dwarnings" }

[tasks.release]
description = "Task to release the package to crates.io"
command = "cargo"
args = ["release", "publish", "--no-verify", "--no-confirm", "--allow-branch \"*\"", "--all-features", "--execute"]
